### ISSUE TITLE
Unable to associate floating IP to instances 

### ISSUE THREAD

**Issue by cesarsotovalero** [wasp-sweden/wara-sw#11]
Hi @gluckzhang, I'm trying to get access to an instance in OpenStack. After following some tutorials I think a floating IP needs to be associate before have a successful ping on the instance from an external network. 

What I want to do is running a web service through the instance using a Docker container.

What I should do?

**Comment by gluckzhang** [comment]
Hi @cesarsotovalero , sorry I didn't notice this issue last week. I need some more information about your issue. What errors did you get? Have you opened the port for ICMP in your network security group?

**Comment by cesarsotovalero** [comment]
Hi @gluckzhang,

I've opened the port for ICMP, as you can see below:

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/13948717/113710952-a59a6100-96e4-11eb-99c0-b5822c83cd5e.png">

Since I want to access the instance via HTTP, I believe that I need to associate a floating IP to my instance (named hercules). However, I got the following error:

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/13948717/113712107-ffe7f180-96e5-11eb-9058-168cc0e7ebd5.png">


Can you try to access one running instance via HTTP and explain how you did?

**Comment by gluckzhang** [comment]
Hi @cesarsotovalero , I see. I think it is related to your network topology. I assume you have made `hercules` directly connected to the external Internet. In this case, you cannot associate a floating IP address with this instance.

One temporary solution is to use the current public IP address instead. This address will not be changed if your instance is running.

*It seems that this IP address does not change even if you reboot or shutdown&restart the instance. I am not sure if this is always the case as I have only tested it once.*

Another solution is to adjust the network topology setup and then associate a floating IP address with this instance. In this case, your instance gets a permanent public IP address. The steps to do this are:

- Visit Project -> Network -> Network Topology
- Create a new Network, e.g., Internal IPv4 Network
- Create a new router and connect the internal network to the external one
- Then move your instance to the internal network by using `Attach/Detach Interface` on page Project -> Compute -> Instances

Here is an example of my network topology setup:
![image](https://user-images.githubusercontent.com/6386131/113714481-b947c680-96e8-11eb-997e-5f6a6a1c6f4c.png)

**Comment by cesarsotovalero** [comment]
I followed your indications and it works now!


<img width="403" alt="image" src="https://user-images.githubusercontent.com/13948717/113717719-332d7f00-96ec-11eb-9e78-c47c0bfbd236.png">


<img width="445" alt="image" src="https://user-images.githubusercontent.com/13948717/113717630-1b55fb00-96ec-11eb-81df-ef37a8203926.png">


This issue is fixed.

Thanks a lot @gluckzhang!

**Comment by gluckzhang** [comment]
My pleasure. Great to see that you have fixed it! :D
